### ISSUE TITLE
Question: Netflix and Disney+ status

### ISSUE THREAD

**Issue by jahirfiquitiva** [elevenvac/elevendev.github.io#3]
Hey,

I came across your website and noticed you're displaying your Netflix and Disney+ activity on it, and wanted to ask you if you would mind sharing or letting me know how you achieve that and what do you use for that?

Thanks in advance!

**Comment by lyertia** [comment]
> Hey,
> 
> I came across your website and noticed you're displaying your Netflix and Disney+ activity on it, and wanted to ask you if you would mind sharing or letting me know how you achieve that and what do you use for that?
> 
> Thanks in advance!

He using Lanyard, 
https://github.com/elevenvac/elevenvac.github.io/blob/main/assets/js/lanyard.js

**Comment by jahirfiquitiva** [comment]
@lyertia yeah, I saw that, but what are they using to connect the Netflix and Disney+ activity to discord? 🤔

**Comment by lyertia** [comment]
> @lyertia yeah, I saw that, but what are they using to connect the Netflix and Disney+ activity to discord? 🤔

And lanyard using discord api. Its simple. Also you have to in their discord guilds.

**Comment by jahirfiquitiva** [comment]
@lyertia I'm aware of how lanyard works, but they did something to show Netflix and Disney+ activity as a Discord status, and that's what I'm interested in knowing how

**Comment by elevenski** [comment]
> @lyertia I'm aware of how lanyard works, but they did something to show Netflix and Disney+ activity as a Discord status, and that's what I'm interested in knowing how

https://premid.app for show Netflix, Disney+ and more platform activity in your Discord status.

**Comment by jahirfiquitiva** [comment]
@elevenvac thank you so much! 😁  ... Does it require you use Netflix or Disney+ on the web browser? It won't work if I use my phone or iPad? 🤔

**Comment by elevenski** [comment]
> @elevenvac thank you so much! 😁 ... Does it require you use Netflix or Disney+ on the web browser? It won't work if I use my phone or iPad? 🤔

it only works on computer and browser.

**Comment by jahirfiquitiva** [comment]
@elevenvac got it, thank you so much! 😀 🙌
